[icons]
Alacritty = "ï„ "
Chrome = "ó°Š¯"
Chromium = "ï‰¨"
Chromium-dev = "îƒ"
Firefox = "ï‰©"
Firefox-nightly = "î…"
Ghostty = "ï„ "
# Gpick = "ï”¿"
Nautilus = "ğŸ“˜"
Nvim = "îš®"
Notification = "ïƒ³"
# TelegramDesktop = "ï‹†"
Terminal = "ï„ "
Termite = "ï„ "
Thunar = "ï»"
Thunderbird = "ïƒ "
VLC = "ó°•¼"
Vim = "î˜«"

# i3 / Xwayland
[aliases.class]
"^(?i)chromium$" = "Chromium"
"^(?i)firefox$" = "Firefox"
"^(?i)com\\.mitchellh\\.ghostty$" = "Ghostty"
"^(?i)org\\.gnome\\.nautilus" = "Nautilus"
# TelegramDesktop = "Telegram"
"(?i)^thunar$" = "Thunar"
"(?i)^vlc$" = "VLC"
"(?i)^xfce4-notifyd$" = "Notification"

# Sway only
[aliases.app_id]
# "^firefox$" = "Firefox"

# i3 only
[aliases.instance]
"open.spotify.com" = "Spotify"

# Both i3 and sway
[aliases.name]
# " . Chromium$" = "Chromium"
# "( . )?Mozilla Firefox$" = "Firefox"
" . Nvim$" = "Nvim"
# " . Thunar$" = "Thunar"
# "^Terminal . .*" = "Terminal"
# FIXME: windows remaining after notification
"(?i)^xfce4-notifyd$" = "Notification"

[general]
separator = ' ï½œ ' # |
# split_at = ":"
# empty_label = ""
# display_property = "app_id"
# display_property = "class"
# display_property = "instance"
display_property = "name"
# default_icon = "ï„‘"

[options]
remove_duplicates = true
no_names = false
no_icon_names = true
focus_fix = false
