---
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s       # Wait before sending first notification
  group_interval: 10s   # Wait before sending batch update
  repeat_interval: 12h  # Resend if still firing
  receiver: 'default'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://ntfy-alertmanager:8080'
        send_resolved: true
